### ISSUE TITLE
How to resolve the 'TypeError: Invalid arguments' error when converting a code with protoc

### ISSUE THREAD

**Issue by leandrozuliani** [thesayyn/protoc-gen-ts#191]
How to resolve the "TypeError: Invalid arguments" error when generating TypeScript code from a .proto file using the protoc compiler?
I am using the "Without Bazel" command as documented in https://www.npmjs.com/package/protoc-gen-ts

C:\Users\user\projects\grcp-login-app\src\app\proto>protoc -I=./ --ts_out=./ login-service.proto
```DeprecationWarning: 'createPropertyDeclaration' has been deprecated since v4.8.0. Decorators have been combined with modifiers. Callers should switch to an overload that does not accept a 'decorators' parameter.
DeprecationWarning: 'createParameterDeclaration' has been deprecated since v4.8.0. Decorators have been combined with modifiers. Callers should switch to an overload that does not accept a 'decorators' parameter.
DeprecationWarning: 'createConstructorDeclaration' has been deprecated since v4.8.0. Decorators are no longer supported for this function. Callers should switch to an overload that does not accept a 'decorators' parameter.
DeprecationWarning: 'createGetAccessorDeclaration' has been deprecated since v4.8.0. Decorators have been combined with modifiers. Callers should switch to an overload that does not accept a 'decorators' parameter.
DeprecationWarning: 'createSetAccessorDeclaration' has been deprecated since v4.8.0. Decorators have been combined with modifiers. Callers should switch to an overload that does not accept a 'decorators' parameter.
DeprecationWarning: 'createMethodDeclaration' has been deprecated since v4.8.0. Decorators have been combined with modifiers. Callers should switch to an overload that does not accept a 'decorators' parameter.
DeprecationWarning: 'createClassDeclaration' has been deprecated since v4.8.0. Decorators have been combined with modifiers. Callers should switch to an overload that does not accept a 'decorators' parameter.
DeprecationWarning: 'createImportDeclaration' has been deprecated since v4.8.0. Decorators are no longer supported for this function. Callers should switch to an overload that does not accept a 'decorators' parameter.
C:\Users\user\AppData\Roaming\npm\node_modules\protoc-gen-ts\node_modules\typescript\lib\typescript.js:172144
            throw new TypeError("Invalid arguments");
            ^

TypeError: Invalid arguments
    at Object.createParameterDeclaration (C:\Users\user\AppData\Roaming\npm\node_modules\protoc-gen-ts\node_modules\typescript\lib\typescript.js:172144:19)
    at createParameter (C:\Users\user\AppData\Roaming\npm\node_modules\protoc-gen-ts\src\rpc.js:154:23)
    at Object.createGrpcInterfaceType (C:\Users\user\AppData\Roaming\npm\node_modules\protoc-gen-ts\src\rpc.js:161:31)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\protoc-gen-ts\src\index.js:55:32)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)

Node.js v18.12.1
--ts_out: protoc-gen-ts: Plugin failed with status code 1.
```

protoc-gen-ts 0.8.5

protoc --version
libprotoc 3.21.12

**Comment by leandrozuliani** [comment]
I successfully installed 'npm i ts-proto' and it worked after running the command 'protoc --plugin=protoc-gen-ts_proto=.\node_modules.bin\protoc-gen-ts_proto.cmd --ts_proto_out=. ./src/protos/*.proto'. 
All the TypeScript files were generated correctly.
Issue closed.
