### ISSUE TITLE
`TypeError: Invalid data` in 0.3.6-rc1+

### ISSUE THREAD

**Issue by sky-lake** [thesayyn/protoc-gen-ts#45]
I was on my way to test #33, but first wanted to verify that my current proto would compile.  Unfortunately, I wasn't able to compile my proto.  It works in 0.3.5 but not 0.3.6-rc1 (tested up through rc4).

Interestingly, it seems to throw this error even if I slim the file down, even all the way down to a totally blank file (though it does give a warning in that case about no syntax specified).  So it doesn't seem to be input related

Here is how I run my proto build:

```bash
PROTOC_GEN_TS_PATH="./node_modules/.bin/protoc-gen-ts" 
TS_OUT_DIR="client-src/ProtoGenerated/"
protoc --plugin="protoc-gen-ts=${PROTOC_GEN_TS_PATH}" --js_out="import_style=commonjs,binary:${TS_OUT_DIR}" --ts_out="${TS_OUT_DIR}" --proto_path=../Bridge/ NetMessage.proto
```

It compiles fine with 0.3.5, but here is the error in the rc's:

```
net.js:714
    throw new TypeError(
    ^

TypeError: Invalid data, chunk must be a string or buffer, not object
    at Socket.write (net.js:714:11)
    at Object.<anonymous> (/path/node_modules/protoc-gen-ts/src/index.js:2199:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path/node_modules/protoc-gen-ts/bin/protoc-gen-ts:3:1)
--ts_out: protoc-gen-ts: Plugin failed with status code 1.
```

package.json contains these dependencies:
```json
"devDependencies": {
    "clean-webpack-plugin": "^3.0.0",
    "css-loader": "^3.4.2",
    "html-webpack-plugin": "^3.2.0",
    "mini-css-extract-plugin": "^0.9.0",
    "ts-loader": "^6.2.1",
    "typescript": "^4.0.2",
    "webpack": "^4.41.5",
    "webpack-cli": "^3.3.10",
	"@types/node": "^12.12.2",
	"protoc-gen-ts": "^0.3.6-rc1"
  },
  "dependencies": {
	  "hotkeys-js": "^3.8.3",
	  "konva": "^7.2.5",
	  "google-protobuf": "^3.15.8",
	  "@microsoft/signalr": "^5.0.5"
  }
```

Which results in these versions:

```
├─┬ @microsoft/signalr@5.0.5
│ ├─┬ abort-controller@3.0.0
│ │ └── event-target-shim@5.0.1
│ ├─┬ eventsource@1.1.0
│ │ └─┬ original@1.0.2
│ │   └─┬ url-parse@1.5.1
│ │     ├── querystringify@2.2.0
│ │     └── requires-port@1.0.0
│ ├─┬ fetch-cookie@0.7.3
│ │ ├── es6-denodeify@0.1.5
│ │ └─┬ tough-cookie@2.5.0
│ │   ├── psl@1.8.0
│ │   └── punycode@2.1.1
│ ├── node-fetch@2.6.1
│ └─┬ ws@6.2.1
│   └── async-limiter@1.0.1
├── @types/node@12.20.11
├─┬ clean-webpack-plugin@3.0.0
│ ├─┬ @types/webpack@4.41.27
│ │ ├── @types/anymatch@1.3.1
│ │ ├── @types/tapable@1.0.7
│ │ ├── @types/uglify-js@3.13.0
│ │ ├─┬ @types/webpack-sources@2.1.0
│ │ │ ├── @types/source-list-map@0.1.2
│ │ │ └── source-map@0.7.3
│ │ └── source-map@0.6.1
│ └─┬ del@4.1.1
│   ├─┬ @types/glob@7.1.3
│   │ └── @types/minimatch@3.0.4
│   ├─┬ globby@6.1.0
│   │ ├─┬ array-union@1.0.2
│   │ │ └── array-uniq@1.0.3
│   │ ├─┬ glob@7.1.6
│   │ │ ├── fs.realpath@1.0.0
│   │ │ ├─┬ inflight@1.0.6
│   │ │ │ └── wrappy@1.0.2
│   │ │ ├─┬ minimatch@3.0.4
│   │ │ │ └─┬ brace-expansion@1.1.11
│   │ │ │   ├── balanced-match@1.0.2
│   │ │ │   └── concat-map@0.0.1
│   │ │ ├── once@1.4.0
│   │ │ └── path-is-absolute@1.0.1
│   │ ├── pify@2.3.0
│   │ └─┬ pinkie-promise@2.0.1
│   │   └── pinkie@2.0.4
│   ├── is-path-cwd@2.2.0
│   ├─┬ is-path-in-cwd@2.1.0
│   │ └─┬ is-path-inside@2.1.0
│   │   └── path-is-inside@1.0.2
│   ├── p-map@2.1.0
│   ├── pify@4.0.1
│   └── rimraf@2.7.1
├─┬ css-loader@3.6.0
│ ├── camelcase@5.3.1
│ ├── cssesc@3.0.0
│ ├── icss-utils@4.1.1
│ ├─┬ loader-utils@1.4.0
│ │ ├── big.js@5.2.2
│ │ ├── emojis-list@3.0.0
│ │ └── json5@1.0.1
│ ├── normalize-path@3.0.0
│ ├── postcss@7.0.35
│ ├── postcss-modules-extract-imports@2.0.0
│ ├─┬ postcss-modules-local-by-default@3.0.3
│ │ └─┬ postcss-selector-parser@6.0.5
│ │   └── util-deprecate@1.0.2
│ ├── postcss-modules-scope@2.2.0
│ ├── postcss-modules-values@3.0.0
│ ├── postcss-value-parser@4.1.0
│ ├─┬ schema-utils@2.7.1
│ │ └── @types/json-schema@7.0.7
│ └── semver@6.3.0
├── google-protobuf@3.15.8
├── hotkeys-js@3.8.3
├─┬ html-webpack-plugin@3.2.0
│ ├─┬ html-minifier@3.5.21
│ │ ├─┬ camel-case@3.0.0
│ │ │ ├─┬ no-case@2.3.2
│ │ │ │ └── lower-case@1.1.4
│ │ │ └── upper-case@1.1.3
│ │ ├── clean-css@4.2.3
│ │ ├── commander@2.17.1
│ │ ├── he@1.2.0
│ │ ├── param-case@2.1.1
│ │ ├── relateurl@0.2.7
│ │ └─┬ uglify-js@3.4.10
│ │   └── commander@2.19.0
│ ├─┬ loader-utils@0.2.17
│ │ ├── big.js@3.2.0
│ │ ├── emojis-list@2.1.0
│ │ ├── json5@0.5.1
│ │ └── object-assign@4.1.1
│ ├── lodash@4.17.21
│ ├─┬ pretty-error@2.1.2
│ │ └─┬ renderkid@2.0.5
│ │   ├─┬ css-select@2.1.0
│ │   │ ├── boolbase@1.0.0
│ │   │ ├── css-what@3.4.2
│ │   │ ├─┬ domutils@1.7.0
│ │   │ │ └─┬ dom-serializer@0.2.2
│ │   │ │   ├── domelementtype@2.2.0
│ │   │ │   └── entities@2.2.0
│ │   │ └── nth-check@1.0.2
│ │   ├─┬ dom-converter@0.2.0
│ │   │ └── utila@0.4.0
│ │   ├─┬ htmlparser2@3.10.1
│ │   │ ├── domelementtype@1.3.1
│ │   │ ├── domhandler@2.4.2
│ │   │ ├── entities@1.1.2
│ │   │ └── readable-stream@3.6.0
│ │   └─┬ strip-ansi@3.0.1
│ │     └── ansi-regex@2.1.1
│ ├── tapable@1.1.3
│ ├── toposort@1.0.7
│ └─┬ util.promisify@1.0.0
│   ├─┬ define-properties@1.1.3
│   │ └── object-keys@1.1.1
│   └─┬ object.getownpropertydescriptors@2.1.2
│     ├─┬ call-bind@1.0.2
│     │ ├── function-bind@1.1.1
│     │ └── get-intrinsic@1.1.1
│     └─┬ es-abstract@1.18.0
│       ├─┬ es-to-primitive@1.2.1
│       │ ├── is-date-object@1.0.2
│       │ └── is-symbol@1.0.3
│       ├── has@1.0.3
│       ├── has-symbols@1.0.2
│       ├── is-callable@1.2.3
│       ├── is-negative-zero@2.0.1
│       ├── is-regex@1.1.2
│       ├── is-string@1.0.5
│       ├── object-inspect@1.10.2
│       ├── object.assign@4.1.2
│       ├── string.prototype.trimend@1.0.4
│       ├── string.prototype.trimstart@1.0.4
│       └─┬ unbox-primitive@1.0.1
│         ├── has-bigints@1.0.1
│         └─┬ which-boxed-primitive@1.0.2
│           ├── is-bigint@1.0.1
│           ├── is-boolean-object@1.1.0
│           └── is-number-object@1.0.4
├── konva@7.2.5
├─┬ mini-css-extract-plugin@0.9.0
│ ├─┬ normalize-url@1.9.1
│ │ ├── prepend-http@1.0.4
│ │ ├─┬ query-string@4.3.4
│ │ │ └── strict-uri-encode@1.1.0
│ │ └─┬ sort-keys@1.1.2
│ │   └── is-plain-obj@1.1.0
│ ├─┬ schema-utils@1.0.0
│ │ └── ajv-errors@1.0.1
│ └─┬ webpack-sources@1.4.3
│   └── source-list-map@2.0.1
├── protoc-gen-ts@0.3.6-rc4
├─┬ ts-loader@6.2.2
│ ├─┬ chalk@2.4.2
│ │ ├─┬ ansi-styles@3.2.1
│ │ │ └─┬ color-convert@1.9.3
│ │ │   └── color-name@1.1.3
│ │ ├── escape-string-regexp@1.0.5
│ │ └── supports-color@5.5.0
│ ├─┬ enhanced-resolve@4.5.0
│ │ ├── graceful-fs@4.2.6
│ │ └─┬ memory-fs@0.5.0
│ │   └─┬ readable-stream@2.3.7
│ │     ├── safe-buffer@5.1.2
│ │     └── string_decoder@1.1.1
│ └─┬ micromatch@4.0.4
│   ├─┬ braces@3.0.2
│   │ └─┬ fill-range@7.0.1
│   │   └─┬ to-regex-range@5.0.1
│   │     └── is-number@7.0.0
│   └── picomatch@2.2.3
├── typescript@4.2.4
├─┬ webpack@4.46.0
│ ├─┬ @webassemblyjs/ast@1.9.0
│ │ ├── @webassemblyjs/helper-wasm-bytecode@1.9.0
│ │ └─┬ @webassemblyjs/wast-parser@1.9.0
│ │   ├── @webassemblyjs/floating-point-hex-parser@1.9.0
│ │   ├── @webassemblyjs/helper-code-frame@1.9.0
│ │   ├── @webassemblyjs/helper-fsm@1.9.0
│ │   └── @xtuc/long@4.2.2
│ ├── @webassemblyjs/helper-module-context@1.9.0
│ ├─┬ @webassemblyjs/wasm-edit@1.9.0
│ │ ├── @webassemblyjs/helper-buffer@1.9.0
│ │ ├── @webassemblyjs/helper-wasm-section@1.9.0
│ │ ├── @webassemblyjs/wasm-gen@1.9.0
│ │ ├── @webassemblyjs/wasm-opt@1.9.0
│ │ └── @webassemblyjs/wast-printer@1.9.0
│ ├─┬ @webassemblyjs/wasm-parser@1.9.0
│ │ ├── @webassemblyjs/helper-api-error@1.9.0
│ │ ├─┬ @webassemblyjs/ieee754@1.9.0
│ │ │ └── @xtuc/ieee754@1.2.0
│ │ ├── @webassemblyjs/leb128@1.9.0
│ │ └── @webassemblyjs/utf8@1.9.0
│ ├── acorn@6.4.2
│ ├─┬ ajv@6.12.6
│ │ ├── fast-deep-equal@3.1.3
│ │ ├── fast-json-stable-stringify@2.1.0
│ │ ├── json-schema-traverse@0.4.1
│ │ └── uri-js@4.4.1
│ ├── ajv-keywords@3.5.2
│ ├── chrome-trace-event@1.0.3
│ ├─┬ eslint-scope@4.0.3
│ │ ├─┬ esrecurse@4.3.0
│ │ │ └── estraverse@5.2.0
│ │ └── estraverse@4.3.0
│ ├── json-parse-better-errors@1.0.2
│ ├── loader-runner@2.4.0
│ ├─┬ memory-fs@0.4.1
│ │ ├─┬ errno@0.1.8
│ │ │ └── prr@1.0.1
│ │ └─┬ readable-stream@2.3.7
│ │   ├── safe-buffer@5.1.2
│ │   └── string_decoder@1.1.1
│ ├─┬ micromatch@3.1.10
│ │ ├── arr-diff@4.0.0
│ │ ├── array-unique@0.3.2
│ │ ├─┬ braces@2.3.2
│ │ │ ├── arr-flatten@1.1.0
│ │ │ ├── extend-shallow@2.0.1
│ │ │ ├─┬ fill-range@4.0.0
│ │ │ │ ├── extend-shallow@2.0.1
│ │ │ │ ├─┬ is-number@3.0.0
│ │ │ │ │ └── kind-of@3.2.2
│ │ │ │ ├── repeat-string@1.6.1
│ │ │ │ └── to-regex-range@2.1.1
│ │ │ ├── repeat-element@1.1.4
│ │ │ ├─┬ snapdragon-node@2.1.1
│ │ │ │ ├─┬ define-property@1.0.0
│ │ │ │ │ └─┬ is-descriptor@1.0.2
│ │ │ │ │   ├── is-accessor-descriptor@1.0.0
│ │ │ │ │   └── is-data-descriptor@1.0.0
│ │ │ │ └─┬ snapdragon-util@3.0.1
│ │ │ │   └─┬ kind-of@3.2.2
│ │ │ │     └── is-buffer@1.1.6
│ │ │ └── split-string@3.1.0
│ │ ├─┬ define-property@2.0.2
│ │ │ ├─┬ is-descriptor@1.0.2
│ │ │ │ ├── is-accessor-descriptor@1.0.0
│ │ │ │ └── is-data-descriptor@1.0.0
│ │ │ └── isobject@3.0.1
│ │ ├─┬ extend-shallow@3.0.2
│ │ │ ├── assign-symbols@1.0.0
│ │ │ └─┬ is-extendable@1.0.1
│ │ │   └── is-plain-object@2.0.4
│ │ ├─┬ extglob@2.0.4
│ │ │ ├─┬ define-property@1.0.0
│ │ │ │ └─┬ is-descriptor@1.0.2
│ │ │ │   ├── is-accessor-descriptor@1.0.0
│ │ │ │   └── is-data-descriptor@1.0.0
│ │ │ ├─┬ expand-brackets@2.1.4
│ │ │ │ ├── define-property@0.2.5
│ │ │ │ ├── extend-shallow@2.0.1
│ │ │ │ └── posix-character-classes@0.1.1
│ │ │ └─┬ extend-shallow@2.0.1
│ │ │   └── is-extendable@0.1.1
│ │ ├─┬ fragment-cache@0.2.1
│ │ │ └── map-cache@0.2.2
│ │ ├── kind-of@6.0.3
│ │ ├─┬ nanomatch@1.2.13
│ │ │ └── is-windows@1.0.2
│ │ ├── object.pick@1.3.0
│ │ ├─┬ regex-not@1.0.2
│ │ │ └─┬ safe-regex@1.1.0
│ │ │   └── ret@0.1.15
│ │ ├─┬ snapdragon@0.8.2
│ │ │ ├─┬ base@0.11.2
│ │ │ │ ├─┬ cache-base@1.0.1
│ │ │ │ │ ├─┬ collection-visit@1.0.0
│ │ │ │ │ │ ├── map-visit@1.0.0
│ │ │ │ │ │ └── object-visit@1.0.1
│ │ │ │ │ ├── get-value@2.0.6
│ │ │ │ │ ├─┬ has-value@1.0.0
│ │ │ │ │ │ └─┬ has-values@1.0.0
│ │ │ │ │ │   ├─┬ is-number@3.0.0
│ │ │ │ │ │   │ └── kind-of@3.2.2
│ │ │ │ │ │   └── kind-of@4.0.0
│ │ │ │ │ ├─┬ set-value@2.0.1
│ │ │ │ │ │ └── extend-shallow@2.0.1
│ │ │ │ │ ├─┬ to-object-path@0.3.0
│ │ │ │ │ │ └── kind-of@3.2.2
│ │ │ │ │ ├── union-value@1.0.1
│ │ │ │ │ └─┬ unset-value@1.0.0
│ │ │ │ │   └─┬ has-value@0.3.1
│ │ │ │ │     ├── has-values@0.1.4
│ │ │ │ │     └── isobject@2.1.0
│ │ │ │ ├─┬ class-utils@0.3.6
│ │ │ │ │ ├── arr-union@3.1.0
│ │ │ │ │ ├── define-property@0.2.5
│ │ │ │ │ └─┬ static-extend@0.1.2
│ │ │ │ │   ├── define-property@0.2.5
│ │ │ │ │   └─┬ object-copy@0.1.0
│ │ │ │ │     ├── copy-descriptor@0.1.1
│ │ │ │ │     ├── define-property@0.2.5
│ │ │ │ │     └── kind-of@3.2.2
│ │ │ │ ├── component-emitter@1.3.0
│ │ │ │ ├─┬ define-property@1.0.0
│ │ │ │ │ └─┬ is-descriptor@1.0.2
│ │ │ │ │   ├── is-accessor-descriptor@1.0.0
│ │ │ │ │   └── is-data-descriptor@1.0.0
│ │ │ │ ├─┬ mixin-deep@1.3.2
│ │ │ │ │ ├── for-in@1.0.2
│ │ │ │ │ └── is-extendable@1.0.1
│ │ │ │ └── pascalcase@0.1.1
│ │ │ ├─┬ debug@2.6.9
│ │ │ │ └── ms@2.0.0
│ │ │ ├─┬ define-property@0.2.5
│ │ │ │ └─┬ is-descriptor@0.1.6
│ │ │ │   ├─┬ is-accessor-descriptor@0.1.6
│ │ │ │   │ └── kind-of@3.2.2
│ │ │ │   ├─┬ is-data-descriptor@0.1.4
│ │ │ │   │ └── kind-of@3.2.2
│ │ │ │   └── kind-of@5.1.0
│ │ │ ├── extend-shallow@2.0.1
│ │ │ ├── source-map@0.5.7
│ │ │ ├─┬ source-map-resolve@0.5.3
│ │ │ │ ├── atob@2.1.2
│ │ │ │ ├── decode-uri-component@0.2.0
│ │ │ │ ├── resolve-url@0.2.1
│ │ │ │ ├── source-map-url@0.4.1
│ │ │ │ └── urix@0.1.0
│ │ │ └── use@3.1.1
│ │ └── to-regex@3.0.2
│ ├─┬ mkdirp@0.5.5
│ │ └── minimist@1.2.5
│ ├── neo-async@2.6.2
│ ├─┬ node-libs-browser@2.2.1
│ │ ├─┬ assert@1.5.0
│ │ │ └─┬ util@0.10.3
│ │ │   └── inherits@2.0.1
│ │ ├─┬ browserify-zlib@0.2.0
│ │ │ └── pako@1.0.11
│ │ ├─┬ buffer@4.9.2
│ │ │ ├── base64-js@1.5.1
│ │ │ ├── ieee754@1.2.1
│ │ │ └── isarray@1.0.0
│ │ ├── console-browserify@1.2.0
│ │ ├── constants-browserify@1.0.0
│ │ ├─┬ crypto-browserify@3.12.0
│ │ │ ├─┬ browserify-cipher@1.0.1
│ │ │ │ ├─┬ browserify-aes@1.2.0
│ │ │ │ │ └── buffer-xor@1.0.3
│ │ │ │ ├─┬ browserify-des@1.0.2
│ │ │ │ │ └── des.js@1.0.1
│ │ │ │ └── evp_bytestokey@1.0.3
│ │ │ ├─┬ browserify-sign@4.2.1
│ │ │ │ ├── bn.js@5.2.0
│ │ │ │ ├── browserify-rsa@4.1.0
│ │ │ │ ├─┬ elliptic@6.5.4
│ │ │ │ │ ├── bn.js@4.12.0
│ │ │ │ │ ├── brorand@1.1.0
│ │ │ │ │ ├── hash.js@1.1.7
│ │ │ │ │ ├── hmac-drbg@1.0.1
│ │ │ │ │ ├── minimalistic-assert@1.0.1
│ │ │ │ │ └── minimalistic-crypto-utils@1.0.1
│ │ │ │ └─┬ parse-asn1@5.1.6
│ │ │ │   └─┬ asn1.js@5.4.1
│ │ │ │     ├── bn.js@4.12.0
│ │ │ │     └── safer-buffer@2.1.2
│ │ │ ├─┬ create-ecdh@4.0.4
│ │ │ │ └── bn.js@4.12.0
│ │ │ ├─┬ create-hash@1.2.0
│ │ │ │ ├── cipher-base@1.0.4
│ │ │ │ ├─┬ md5.js@1.3.5
│ │ │ │ │ └── hash-base@3.1.0
│ │ │ │ ├── ripemd160@2.0.2
│ │ │ │ └── sha.js@2.4.11
│ │ │ ├── create-hmac@1.1.7
│ │ │ ├─┬ diffie-hellman@5.0.3
│ │ │ │ ├── bn.js@4.12.0
│ │ │ │ └─┬ miller-rabin@4.0.1
│ │ │ │   └── bn.js@4.12.0
│ │ │ ├── inherits@2.0.4
│ │ │ ├── pbkdf2@3.1.2
│ │ │ ├─┬ public-encrypt@4.0.3
│ │ │ │ └── bn.js@4.12.0
│ │ │ ├── randombytes@2.1.0
│ │ │ └── randomfill@1.0.4
│ │ ├── domain-browser@1.2.0
│ │ ├── events@3.3.0
│ │ ├── https-browserify@1.0.0
│ │ ├── os-browserify@0.3.0
│ │ ├── path-browserify@0.0.1
│ │ ├── process@0.11.10
│ │ ├── punycode@1.4.1
│ │ ├── querystring-es3@0.2.1
│ │ ├─┬ readable-stream@2.3.7
│ │ │ ├── core-util-is@1.0.2
│ │ │ ├── process-nextick-args@2.0.1
│ │ │ ├── safe-buffer@5.1.2
│ │ │ └── string_decoder@1.1.1
│ │ ├─┬ stream-browserify@2.0.2
│ │ │ └─┬ readable-stream@2.3.7
│ │ │   ├── safe-buffer@5.1.2
│ │ │   └── string_decoder@1.1.1
│ │ ├─┬ stream-http@2.8.3
│ │ │ ├── builtin-status-codes@3.0.0
│ │ │ ├─┬ readable-stream@2.3.7
│ │ │ │ ├── safe-buffer@5.1.2
│ │ │ │ └── string_decoder@1.1.1
│ │ │ ├── to-arraybuffer@1.0.1
│ │ │ └── xtend@4.0.2
│ │ ├─┬ string_decoder@1.3.0
│ │ │ └── safe-buffer@5.2.1
│ │ ├─┬ timers-browserify@2.0.12
│ │ │ └── setimmediate@1.0.5
│ │ ├── tty-browserify@0.0.0
│ │ ├─┬ url@0.11.0
│ │ │ ├── punycode@1.3.2
│ │ │ └── querystring@0.2.0
│ │ ├─┬ util@0.11.1
│ │ │ └── inherits@2.0.3
│ │ └── vm-browserify@1.1.2
│ ├── schema-utils@1.0.0
│ ├─┬ terser-webpack-plugin@1.4.5
│ │ ├─┬ cacache@12.0.4
│ │ │ ├── bluebird@3.7.2
│ │ │ ├── chownr@1.1.4
│ │ │ ├── figgy-pudding@3.5.2
│ │ │ ├── infer-owner@1.0.4
│ │ │ ├─┬ lru-cache@5.1.1
│ │ │ │ └── yallist@3.1.1
│ │ │ ├─┬ mississippi@3.0.0
│ │ │ │ ├─┬ concat-stream@1.6.2
│ │ │ │ │ ├─┬ readable-stream@2.3.7
│ │ │ │ │ │ ├── safe-buffer@5.1.2
│ │ │ │ │ │ └── string_decoder@1.1.1
│ │ │ │ │ └── typedarray@0.0.6
│ │ │ │ ├─┬ duplexify@3.7.1
│ │ │ │ │ ├─┬ readable-stream@2.3.7
│ │ │ │ │ │ ├── safe-buffer@5.1.2
│ │ │ │ │ │ └── string_decoder@1.1.1
│ │ │ │ │ └── stream-shift@1.0.1
│ │ │ │ ├── end-of-stream@1.4.4
│ │ │ │ ├─┬ flush-write-stream@1.1.1
│ │ │ │ │ └─┬ readable-stream@2.3.7
│ │ │ │ │   ├── safe-buffer@5.1.2
│ │ │ │ │   └── string_decoder@1.1.1
│ │ │ │ ├─┬ from2@2.3.0
│ │ │ │ │ └─┬ readable-stream@2.3.7
│ │ │ │ │   ├── safe-buffer@5.1.2
│ │ │ │ │   └── string_decoder@1.1.1
│ │ │ │ ├─┬ parallel-transform@1.2.0
│ │ │ │ │ ├── cyclist@1.0.1
│ │ │ │ │ └─┬ readable-stream@2.3.7
│ │ │ │ │   ├── safe-buffer@5.1.2
│ │ │ │ │   └── string_decoder@1.1.1
│ │ │ │ ├── pump@3.0.0
│ │ │ │ ├─┬ pumpify@1.5.1
│ │ │ │ │ └── pump@2.0.1
│ │ │ │ ├── stream-each@1.2.3
│ │ │ │ └─┬ through2@2.0.5
│ │ │ │   └─┬ readable-stream@2.3.7
│ │ │ │     ├── safe-buffer@5.1.2
│ │ │ │     └── string_decoder@1.1.1
│ │ │ ├─┬ move-concurrently@1.0.1
│ │ │ │ ├── aproba@1.2.0
│ │ │ │ ├─┬ copy-concurrently@1.0.5
│ │ │ │ │ └── iferr@0.1.5
│ │ │ │ ├─┬ fs-write-stream-atomic@1.0.10
│ │ │ │ │ ├── imurmurhash@0.1.4
│ │ │ │ │ └─┬ readable-stream@2.3.7
│ │ │ │ │   ├── safe-buffer@5.1.2
│ │ │ │ │   └── string_decoder@1.1.1
│ │ │ │ └── run-queue@1.0.3
│ │ │ ├── promise-inflight@1.0.1
│ │ │ ├── ssri@6.0.2
│ │ │ └─┬ unique-filename@1.1.1
│ │ │   └── unique-slug@2.0.2
│ │ ├─┬ find-cache-dir@2.1.0
│ │ │ ├── commondir@1.0.1
│ │ │ └─┬ make-dir@2.1.0
│ │ │   └── semver@5.7.1
│ │ ├── is-wsl@1.1.0
│ │ ├── schema-utils@1.0.0
│ │ ├── serialize-javascript@4.0.0
│ │ ├─┬ terser@4.8.0
│ │ │ ├── commander@2.20.3
│ │ │ └─┬ source-map-support@0.5.19
│ │ │   └── buffer-from@1.1.1
│ │ └── worker-farm@1.7.0
│ └─┬ watchpack@1.7.5
│   ├─┬ chokidar@3.5.1
│   │ ├── anymatch@3.1.2
│   │ ├── UNMET OPTIONAL DEPENDENCY fsevents@~2.3.1
│   │ ├── glob-parent@5.1.2
│   │ ├─┬ is-binary-path@2.1.0
│   │ │ └── binary-extensions@2.2.0
│   │ └── readdirp@3.5.0
│   └─┬ watchpack-chokidar2@2.0.1
│     └─┬ chokidar@2.1.8
│       ├─┬ anymatch@2.0.0
│       │ ├── micromatch@3.1.10
│       │ └─┬ normalize-path@2.1.1
│       │   └── remove-trailing-separator@1.1.0
│       ├── async-each@1.0.3
│       ├─┬ braces@2.3.2
│       │ ├── extend-shallow@2.0.1
│       │ └─┬ fill-range@4.0.0
│       │   ├── extend-shallow@2.0.1
│       │   ├─┬ is-number@3.0.0
│       │   │ └── kind-of@3.2.2
│       │   └── to-regex-range@2.1.1
│       ├── UNMET OPTIONAL DEPENDENCY fsevents@^1.2.7
│       ├─┬ glob-parent@3.1.0
│       │ ├── is-glob@3.1.0
│       │ └── path-dirname@1.0.2
│       ├─┬ is-binary-path@1.0.1
│       │ └── binary-extensions@1.13.1
│       ├─┬ readdirp@2.2.1
│       │ └─┬ readable-stream@2.3.7
│       │   ├── safe-buffer@5.1.2
│       │   └── string_decoder@1.1.1
│       └── upath@1.2.0
└─┬ webpack-cli@3.3.12
  ├─┬ cross-spawn@6.0.5
  │ ├── nice-try@1.0.5
  │ ├── path-key@2.0.1
  │ ├── semver@5.7.1
  │ ├─┬ shebang-command@1.2.0
  │ │ └── shebang-regex@1.0.0
  │ └─┬ which@1.3.1
  │   └── isexe@2.0.0
  ├─┬ findup-sync@3.0.0
  │ ├── detect-file@1.0.0
  │ ├─┬ is-glob@4.0.1
  │ │ └── is-extglob@2.1.1
  │ ├─┬ micromatch@3.1.10
  │ │ └─┬ braces@2.3.2
  │ │   ├── extend-shallow@2.0.1
  │ │   └─┬ fill-range@4.0.0
  │ │     ├── extend-shallow@2.0.1
  │ │     ├─┬ is-number@3.0.0
  │ │     │ └── kind-of@3.2.2
  │ │     └── to-regex-range@2.1.1
  │ └─┬ resolve-dir@1.0.1
  │   ├─┬ expand-tilde@2.0.2
  │   │ └─┬ homedir-polyfill@1.0.3
  │   │   └── parse-passwd@1.0.0
  │   └─┬ global-modules@1.0.0
  │     └── global-prefix@1.0.2
  ├─┬ global-modules@2.0.0
  │ └─┬ global-prefix@3.0.0
  │   └── ini@1.3.8
  ├─┬ import-local@2.0.0
  │ ├── pkg-dir@3.0.0
  │ └─┬ resolve-cwd@2.0.0
  │   └── resolve-from@3.0.0
  ├── interpret@1.4.0
  ├─┬ supports-color@6.1.0
  │ └── has-flag@3.0.0
  ├── v8-compile-cache@2.3.0
  └─┬ yargs@13.3.2
    ├─┬ cliui@5.0.0
    │ ├─┬ strip-ansi@5.2.0
    │ │ └── ansi-regex@4.1.0
    │ └─┬ wrap-ansi@5.1.0
    │   └─┬ strip-ansi@5.2.0
    │     └── ansi-regex@4.1.0
    ├─┬ find-up@3.0.0
    │ └─┬ locate-path@3.0.0
    │   ├─┬ p-locate@3.0.0
    │   │ └─┬ p-limit@2.3.0
    │   │   └── p-try@2.2.0
    │   └── path-exists@3.0.0
    ├── get-caller-file@2.0.5
    ├── require-directory@2.1.1
    ├── require-main-filename@2.0.0
    ├── set-blocking@2.0.0
    ├─┬ string-width@3.1.0
    │ ├── emoji-regex@7.0.3
    │ ├── is-fullwidth-code-point@2.0.0
    │ └─┬ strip-ansi@5.2.0
    │   └── ansi-regex@4.1.0
    ├── which-module@2.0.0
    ├── y18n@4.0.3
    └─┬ yargs-parser@13.1.2
      └── decamelize@1.2.0
```

**Comment by thesayyn** [comment]
that seems odd. looks like the plugin is working at all. probably a connectivity issue between protoc and the plugin.

can you also, tell me more about the protoc version you are using and whether it is preinstalled or installed via npm package?

**Comment by sky-lake** [comment]
Sure,

I appear to be using the snap version of protoc.  (I think probably went this route because the official distro version is even more old).

```bash
$ which protoc
/snap/bin/protoc
$ protoc --version
libprotoc 3.14.0
```

I tried downloading the most recent protoc from github, but still got the same error:

```bash
/home/<user>/Downloads/protoc-3.15.8-linux-x86_64/bin/protoc --plugin="protoc-gen-ts=${PROTOC_GEN_TS_PATH}" --js_out="import_style=commonjs,binary:${TS_OUT_DIR}" --ts_out="${TS_OUT_DIR}" --proto_path=../Bridge/ NetMessage.proto
net.js:714
    throw new TypeError(
    ^
TypeError: Invalid data, chunk must be a string or buffer, not object
<same callstack as before>
```

**Comment by thesayyn** [comment]
That seems odd. I'll take a look at it as soon as possible.
Right now I am focused on landing support for oneof fields then I'll get to this.

Feel free to send a PR for this.

**Comment by thesayyn** [comment]
Hey @sky-lake

"0.3.6-rc5" has been released. Can you give it a try and let me know if the issue persists?

**Comment by thesayyn** [comment]
For now, I am closing this issue for housecleaning. Feel free to reopen if the problem persists.
