### ISSUE TITLE
Cannot compile.

### ISSUE THREAD

**Issue by ivan-shaban** [thesayyn/protoc-gen-ts#8]
Hello, i'm trying to use you library and it fails at start, probably i miss something in configuration, can you give me advice?
```
>protoc -I=protos --ts_out=javascript/new-dist my.proto
internal/modules/cjs/loader.js:984
  throw err;
  ^

Error: Cannot find module 'google-protobuf/google/protobuf/compiler/plugin_pb'
Require stack:
- C:\Users\...\AppData\Roaming\nvm\v12.16.0\node_modules\protoc-gen-ts\index.js
- C:\Users\...\AppData\Roaming\nvm\v12.16.0\node_modules\protoc-gen-ts\bin\protoc-gen-ts
?[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:863:27)?[39m
?[90m    at Module.require (internal/modules/cjs/loader.js:1043:19)?[39m
?[90m    at require (internal/modules/cjs/helpers.js:77:18)?[39m
    at Object.<anonymous> (C:\Users\...\AppData\Roaming\nvm\v12.16.0\node_modules\?[4mprotoc-gen-ts?[24m\index.js:1:16)
?[90m    at Module._compile (internal/modules/cjs/loader.js:1157:30)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:1001:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:900:14)?[39m
?[90m    at Module.require (internal/modules/cjs/loader.js:1043:19)?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  requireStack: [
    ?[32m'C:\\Users\\...\\AppData\\Roaming\\nvm\\v12.16.0\\node_modules\\protoc-gen-ts\\index.js'?[39m,
    ?[32m'C:\\Users\\...\\AppData\\Roaming\\nvm\\v12.16.0\\node_modules\\protoc-gen-ts\\bin\\protoc-gen-ts'?[39m
  ]
}
--ts_out: protoc-gen-ts: Plugin failed with status code 1.
```
Protoc version:
```
>protoc --version
libprotoc 3.11.4
```

**Comment by thesayyn** [comment]
Hey @ivan-shaban.

I guess your problem is related to a missing peer dependency.

Could you please also send here your package.json file?

**Comment by ivan-shaban** [comment]
```
{
  "name": "library",
  "version": "0.0.1-branch.0",
  "module": "dist/index.js",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "files": [
    "dist/"
  ],
  "scripts": {
    "release": "npm version prerelease --preid=branch"
  },
  "devDependencies": {
    "jsdoc": "3.6.3",
    "npm-run-all": "^4.1.5",
    "rimraf": "^2.7.1"
  },
  "dependencies": {
    "protoc-gen-ts": "0.0.5",
    "typescript": "^3.7.2",
    "google-protobuf": "^3.11.0-rc.2"
  }
}
```
Also I cannot manually install bazel library which defined as you peer dependency

**Comment by thesayyn** [comment]
I'm glad that you solved the problem.
 I'm going to close this issue but I will add this as a warning into the documentation.
Feel free to reopen the issue if you have further questions.
